// If using a module system (e.g. via vue-cli), import Vue and VueI18n and then call Vue.use(VueI18n).
// import Vue from 'vue'
// import VueI18n from 'vue-i18n'
//
// Vue.use(VueI18n)

// Ready translated locale messages
const messages = {
    zh: {
      lan: {
        hello:'HELLO hk',
        orderDetail:'訂單詳情',
        payAmt:'付款金額',
        exchangeQuantity:'兌換數量',
        paymentSystem:'支付系統',
        currency:'幣種',
        continue:'繼續',
        prevStep:'上一步',
        nextStep:'下一步',
        SelectPaymentMethod:'選擇您的付款方式',
        enterBankAccHolderName:'輸入轉賬銀行卡持有人姓名的',
        enterBankAccHolderRealName:'輸入轉賬銀行卡持有人的真實姓名',
        followInsturctionAndPayEnoughAmt:'請根據提示進行轉賬，務必按照付款金額足額支付',
        plsWaitDuringProcess:'請稍等，現正整合交易者資料',
        buyOrder:'購買訂單',
        cannotFindTheMatchYet:'暫時未找到合適配對',
        systemWillTryAgainSoon:'系統會在稍後重新嘗試',
        businessName:'商家名',
        remindTimeOfOrderPayment:'訂單剩餘支付時間',
        longlong:'以下信息為幣商的指定收款賬戶，',
        longlong2:'請務必按照規則操作，網銀轉賬到以下賬戶。',
        receiverName:'收款姓名',
        receiverAcc:'收款賬號',
        bankOfAcc:'開戶銀行',
        LocateState:'所在省市',
        no1:'1.',
        no2:'2.',
        no3:'3.',
        no4:'4.',
        unionPayRules1:'網銀轉賬時 -禁止在網銀備注填寫任何文字',
        unionPayRules2:'轉賬後請保留轉賬截圖',
        unionPayRules3:'轉賬後請務必點擊確認已付款',
        unionPayRules4:'每筆交易均需酌收手續費用，請詢問您的錢包平台商',
        unionPayRules5:'交易進行中, 等候授權時間約1-2分鐘, 等待過程請勿重置頁面',
        uploadReceipt:'上載憑證',
        uploadPaymentProof:'上載付款證明',
        confirmComplete:'確定完成',
        transactionCompleted:'轉帳已完成',
        submitSuccess:'交易已完成',
        announcementAfterTranaction:'購買成功後，數字貨幣將全額充值到您要付款的商戶，完成付款',
        announcementAfterTranactionTime:'訂單已開始處理，預計到賬時間：15分鐘內',
        mins:'分',
        sec:'秒',
        timeoutMsg:'已逾時，請返回商戶或重申填寫。',
        onlineBank:'網銀',
        visaMaster:'VISA/ MASTER',
        alipay:'支付寶',
        paypal:'PAYPAL',
        rmb:'人民幣',
        usd:'美元',
        jpy:'日元',
        krw:'韓元',
        eur:'歐元',
        myr:'馬幣',
        remarkHints:'選擇您的付款方式：銀行卡',
        preloginBank:'請預先登入轉賬用的網上銀行。',
        back:'返回',
        paymentAddress:'收款地址',
        payAttentionToResult:'入金操作完成，請留意訂單結果。',
        enterAlipayHolderName:'輸入支付寶持有人姓名的',
        enterAlipayHolderRealName:'輸入支付寶持有人的真實姓名',
        plsEnterOrderCode:'請輸入訂單號碼',
        transactionFailed:'很抱歉, 交易尚未完成, 請查詢錢包提供商',
        waitTransaction1min:'交易進行中, 等候授權時間約1-2分鐘, 等待過程請勿重置頁面',
        upload:'上載',
        uploadWithClearAddr:'請上存轉賬憑證 (清晰轉賬地址)',
        bank:'銀行',
      }
    },
    en: {
        lan: {
            hello:'HELLO en',
            orderDetail:'Order Details',
            payAmt:'Payment Amount',
            exchangeQuantity:'Equivalent',
            paymentSystem:'Pay with',
            currency:'Currency',
            continue:'Continue',
            prevStep:'Back',
            nextStep:'Next',
            SelectPaymentMethod:'Select your Payment Method',
            enterBankAccHolderName:'Please put down the Name of the Bank Account holder',
            enterBankAccHolderRealName:'Please enter the REAL name of the Card Holder',
            followInsturctionAndPayEnoughAmt:'Please transfer the exact amount from the Instructions underneath',
            plsWaitDuringProcess:'Transfer matching in progress. Please wait.',
            buyOrder:'Buy order',
            cannotFindTheMatchYet:'Unable match the Trade',
            systemWillTryAgainSoon:'System Automatically will attempte soon',
            businessName:'Business name',
            remindTimeOfOrderPayment:'Please complete the transaction in',
            longlong:'Below is the Payee Details. ',
            longlong2:'Please transfer the exact amount to the following account with your own online bank',
            receiverName:'Payee Name',
            receiverAcc:'Bank Account Number',
            bankOfAcc:'Bank Name',
            LocateState:'Bank Location',
            no1:'1.',
            no2:'2.',
            no3:'3.',
            no4:'4.',
            unionPayRules1:'Please Never enter any words under Remark field during transfer',
            unionPayRules2:'Please keep the Transfer Screenshot after transfer completed',
            unionPayRules3:'Must click to COMPLETED button after transfer',
            unionPayRules4:'Each transaction incurred transaction fees. The transaction fees kindly ask your wallet platform',
            unionPayRules5:'We are processing your transaction, do not click away from this page. This process can take up to 1-2 minutes.',
            uploadReceipt:'Upload Receipt',
            uploadPaymentProof:'Upload Transfer Receipt',
            confirmComplete:'Completed',
            transactionCompleted:'Transfer Completed',
            submitSuccess:'Transaction Completed',
            announcementAfterTranaction:'All credits will directly deposit to the merchant account after transfer has been made',
            announcementAfterTranactionTime:'Order is in progress. Credits expected to deposit within 15mins',
            mins:':',
            sec:'',
            timeoutMsg:'Time Out, please restart your transfer application',
            onlineBank:'Online Banking',
            visaMaster:'VISA/MASTER',
            alipay:'Alipay',
            paypal:'PAYPAL',
            rmb:'RMB',
            usd:'USD',
            jpy:'JPY',
            krw:'KRW',
            myr:'MYR',
            eur:'EUR',
            remarkHints:'Select your pay method: Online Bank',
            preloginBank:'To ready up your transfer. Please login to you online bank',
            back:'Back',
            paymentAddress:'Address',
            payAttentionToResult:'入金操作完成，請留意訂單結果。',
            enterAlipayHolderName:'輸入支付寶持有人姓名的',
            enterAlipayHolderRealName:'輸入支付寶持有人的真實姓名',
            plsEnterOrderCode:'',
            transactionFailed:'Sorry, the transaction has not been completed yet, please check with the wallet provider.',
            waitTransaction1min:'We are processing your transaction, do not click away from this page. This process can take up to 1-2 minutes.',
            upload:'upload',
            uploadWithClearAddr:'Please upload receipt with clear transaction address',
            bank:'Bank',
          }
      },
    jp: {
        lan: {
            hello:'HELLO jp',
            orderDetail:'注文詳細',
            payAmt:'支払金額',
            exchangeQuantity:'両替数量',
            paymentSystem:'支払システム',
            currency:'通貨種類',
            continue:'継続する',
            prevStep:'戻る',
            nextStep:'次へ',
            SelectPaymentMethod:'お支払方法をお選びください',
            enterBankAccHolderName:'振替の銀行カードの所有者名を入力してください',
            enterBankAccHolderRealName:'振替の銀行カードの所有者実名を入力してください',
            followInsturctionAndPayEnoughAmt:'提示に従って振替を行ってください；是非支払金額を全額でお支払いください',
            plsWaitDuringProcess:'少々お待ちください、ただいまトレーダーの資料をまとめています',
            buyOrder:'注文',
            cannotFindTheMatchYet:'適切なマッチはまだ見つかりません',
            systemWillTryAgainSoon:'系統會在稍後重新嘗試',
            businessName:'事業者名',
            remindTimeOfOrderPayment:'注文の残りの支払い時間',
            longlong:'以下の情報は貨幣商の指定入金口座です。',
            longlong2:'必ず規則通り操作してください。ネット銀行で以下の口座に振り込でください。',
            receiverName:'入金者名',
            receiverAcc:'入金口座',
            bankOfAcc:'口座銀行',
            LocateState:'所属地域',
            no1:'1.',
            no2:'2.',
            no3:'3.',
            no4:'4.',
            unionPayRules1:'ネット銀行で送金する時-何の注の付加も禁止されます。',
            unionPayRules2:'振替後のスクリーンショットをお残し下さい。',
            unionPayRules3:'振替後は振替完了を必ずクリックしてください。',
            unionPayRules4:'各取引には手数料を生じますので、ご利用のウォレットプラットフォームプロバイダーにお問い合わせくださいませ。',
            unionPayRules5:'取引中、承認時間を約1〜2分お待ち頂き、待機中にはページをリセットしないでください。',
            uploadReceipt:'送金証明書をアップロードする',
            uploadPaymentProof:'送金証明書をアップロードする',
            confirmComplete:'確定後完成する',
            transactionCompleted:'振替完了',
            submitSuccess:'取引完了',
            announcementAfterTranaction:'ゲームポイントはアップロード中、お待ちください',
            announcementAfterTranactionTime:'',
            mins:'分',
            sec:'秒',
            timeoutMsg:'時間を超過するので、事業者に戻って、あるいは改めて入力してください。',
            onlineBank:'ネット銀行',
            visaMaster:'VISA/ MASTER',
            alipay:'アリペイ',
            paypal:'PAYPAL',
            rmb:'人民元',
            usd:'ドル',
            jpy:'日本円',
            myr:'MYR',
            krw:'ウォン',
            eur:'ユーロ',
            remarkHints:'支払い方法をお選んでください：ネット銀行',
            preloginBank:'御使用のネット銀行口座にご登録ください。',
            back:'戻る',
            paymentAddress:'入金アドレス',
            payAttentionToResult:'入金操作は完了しました。注文の結果にご注意ください。',
            enterAlipayHolderName:'アリペイ所有者のお名前を入力してください。',
            enterAlipayHolderRealName:'アリペイ所有者の本名を入力してください。',
            plsEnterOrderCode:'請輸入訂單號碼',
            transactionFailed:'申し訳ありませんが、取引はまだ完了しておりません。お手数お挂け致しますが、ウォレットプロバイダーまでお问合せくださいませ。',
            waitTransaction1min:'取引中、承認時間を約1〜2分お待ち頂き、待機中にはページをリセットしないでください。',
            upload:'アップロードする',
            uploadWithClearAddr:'振込詳細をアップロードしてお願い致します。（振込アドレスを明確にしてください。）',
            bank:'銀行',
        }
    }
}
